import { removeFile, writeFileAtomic } from '../util/fs.js';
import { configPathFor, secretEnvPathFor } from './paths.js';
import type {
  ApprovalPolicy,
  ApprovalsReviewer,
  AuthMethod,
  SandboxMode,
  WireApi,
} from './profile.js';

export interface ProfileSettingsSpec {
  custom: boolean;
  baseUrl?: string;
  authMethod?: AuthMethod;
  /** Wire protocol for the custom provider. Defaults to 'responses'. */
  wireApi?: WireApi;
  /** Secret value. Only written to the profile's .env file. */
  secret?: string;
  model?: string;
  approvalPolicy?: ApprovalPolicy;
  sandboxMode?: SandboxMode;
  approvalsReviewer?: ApprovalsReviewer;
  providerId?: string;
  envVar?: string;
}

export interface ProfileFiles {
  configPath: string;
  secretEnvPath?: string;
  providerId?: string;
  envVar?: string;
}

function sanitizeId(value: string): string {
  const id = value.replace(/[^A-Za-z0-9_]/g, '_').replace(/^_+|_+$/g, '');
  const fallback = id.length > 0 ? id : 'profile';
  return /^[A-Za-z_]/.test(fallback) ? fallback : `profile_${fallback}`;
}

export function providerIdForAlias(alias: string): string {
  return sanitizeId(alias).toLowerCase();
}

export function envVarForAlias(alias: string): string {
  return `CODEX_SWITCH_${sanitizeId(alias).toUpperCase()}_API_KEY`;
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}

function tomlKeyPath(key: string): string {
  return key
    .split('.')
    .map((part) => (/^[A-Za-z_][A-Za-z0-9_]*$/.test(part) ? part : tomlString(part)))
    .join('.');
}

function tomlInlineTable(value: Record<string, string>): string {
  return `{ ${Object.entries(value)
    .map(([key, v]) => `${tomlString(key)} = ${tomlString(v)}`)
    .join(', ')} }`;
}

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`;
}

export function buildSecretEnv(spec: ProfileSettingsSpec): string | null {
  const authMethod = spec.authMethod ?? 'envKey';
  if (!spec.custom || authMethod === 'none' || !spec.secret || !spec.envVar) return null;

  const value =
    authMethod === 'bearerHeader' && !/^Bearer\s+/i.test(spec.secret)
      ? `Bearer ${spec.secret}`
      : spec.secret;

  return [
    `# Generated by codex-switch.`,
    `export ${spec.envVar}=${shellSingleQuote(value)}`,
    '',
  ].join('\n');
}

export function buildConfigToml(spec: ProfileSettingsSpec): string {
  const lines = [
    '# Generated by codex-switch.',
    '# This file is the CODEX_HOME-local configuration for this launcher profile.',
    'cli_auth_credentials_store = "file"',
  ];

  if (spec.model) lines.push(`model = ${tomlString(spec.model)}`);
  if (spec.approvalPolicy) lines.push(`approval_policy = ${tomlString(spec.approvalPolicy)}`);
  if (spec.approvalsReviewer) {
    lines.push(`approvals_reviewer = ${tomlString(spec.approvalsReviewer)}`);
  }
  if (spec.sandboxMode) lines.push(`sandbox_mode = ${tomlString(spec.sandboxMode)}`);

  if (spec.custom) {
    if (!spec.baseUrl) throw new Error('Custom provider profiles require a base URL.');
    const authMethod = spec.authMethod ?? 'envKey';
    const providerId = spec.providerId ?? providerIdForAlias('profile');
    lines.push(`model_provider = ${tomlString(providerId)}`);

    // Codex 0.140+ injects a `multi_agent` sub-agent tool group (a Responses
    // tool of `type = "namespace"`). Non-OpenAI Responses gateways such as
    // OpenRouter reject the unknown variant with HTTP 422 ("unknown variant
    // `namespace`"), which breaks the first turn. Disable it for custom
    // providers. Must stay above the [model_providers.*] table so the bare
    // keys below are not absorbed into [features].
    lines.push('');
    lines.push('[features]');
    lines.push('multi_agent = false');
    lines.push('multi_agent_v2 = false');

    lines.push('');
    lines.push(`[model_providers.${tomlKeyPath(providerId)}]`);
    lines.push(`name = ${tomlString(providerId)}`);
    lines.push(`base_url = ${tomlString(spec.baseUrl)}`);
    lines.push(`wire_api = ${tomlString(spec.wireApi ?? 'responses')}`);

    if (authMethod === 'envKey') {
      if (!spec.envVar) throw new Error('env_key authentication requires an env var name.');
      lines.push(`env_key = ${tomlString(spec.envVar)}`);
    } else if (authMethod === 'bearerHeader') {
      if (!spec.envVar) throw new Error('Bearer header authentication requires an env var name.');
      lines.push(`env_http_headers = ${tomlInlineTable({ Authorization: spec.envVar })}`);
    } else if (authMethod === 'xApiKeyHeader') {
      if (!spec.envVar) throw new Error('X-Api-Key authentication requires an env var name.');
      lines.push(`env_http_headers = ${tomlInlineTable({ 'X-Api-Key': spec.envVar })}`);
    }
  }

  return `${lines.join('\n')}\n`;
}

export function writeProfileSettings(alias: string, spec: ProfileSettingsSpec): ProfileFiles {
  const authMethod = spec.custom ? (spec.authMethod ?? 'envKey') : spec.authMethod;
  const providerId = spec.custom ? (spec.providerId ?? providerIdForAlias(alias)) : undefined;
  const envVar =
    spec.custom && authMethod !== 'none' ? (spec.envVar ?? envVarForAlias(alias)) : undefined;
  const resolved = { ...spec, authMethod, providerId, envVar };

  const configPath = configPathFor(alias);
  writeFileAtomic(configPath, buildConfigToml(resolved), 0o600);

  const secretEnv = buildSecretEnv(resolved);
  const secretEnvPath = secretEnvPathFor(alias);
  if (secretEnv) {
    writeFileAtomic(secretEnvPath, secretEnv, 0o600);
  } else {
    removeFile(secretEnvPath);
  }

  return {
    configPath,
    secretEnvPath: secretEnv ? secretEnvPath : undefined,
    providerId,
    envVar,
  };
}
